### ISSUE TITLE
Create event rules in cloudformation template

### ISSUE THREAD

**Issue by johnktims** [arabold/aws-to-slack#75]
Would you accept a PR for this?

I would add a condition so that users can opt out. Something like:
```
  EnableCodeBuildEvents:
    Type: String
    Description: 'Create cloudwatch rule for codebuild events'
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
```
and then add something like the event rules defined in https://hackernoon.com/monitor-your-aws-codebuilds-via-lambda-and-slack-ae2c621f68f1
