### ISSUE TITLE
Incorrect region for the S3 location for the Lambda function

### ISSUE THREAD

**Issue by txynidakis** [arabold/aws-to-slack#83]
Hi 
I'm (hopefully) following the instruction.

I encountered the below issue while creating the stack.

Error occurred while GetObject. S3 Error Code: AuthorizationHeaderMalformed. S3 Error Message: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'ap-southeast-2' (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 4f02d0d7-e5ee-4971-94c2-dc837b35e620)

I've rebuild the release using 
`AWS_REGION="ap-southeast-2" LAMBDA_NAME="cloudwatch-to-slack" make deploy  `

I've changed the CF template to
```yaml
Timeout: 15 # Cross-region metrics lookup requires at least 10s
Code:
  S3Bucket: xxxx-xxx-xxxxxxx
  S3Key: Lambda/release.zip
```
are you able to provide some assistance please?
